---
title: Portfolio 2018
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Sharon Chen
description: Sharon Chen Design Portfolio
author: Sharon Chen
author_email: sharonch3n@gmail.com
category_dir: "/"
baseurl: "sharonchen.design"
url: http://sharonchen.design
markdown: kramdown
permalink: pretty
paginate: 8
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
future: true
encoding: UTF-8
